In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn import linear_model

In [2]:
def laserToCart(scan):
    for ang, dist in enumerate(scan[0:-1]):
        ang += 180
        if dist == 0.0:
            continue
        x = dist * np.cos(ang * np.pi / 180)
        y = dist * np.sin(ang * np.pi / 180)
        try:
            pts = np.append(pts, [[x,y]], axis=0)
        except:
            pts = np.asarray([[x,y]])
    return (pts)

In [50]:
scan1 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0479999780654907, 1.034000039100647, 1.0199999809265137, 1.00600004196167, 0.9940000176429749, 0.0, 0.968999981880188, 0.9580000042915344, 0.9480000138282776, 0.9380000233650208, 0.9330000281333923, 0.9200000166893005, 0.9139999747276306, 0.906000018119812, 0.8960000276565552, 0.8889999985694885, 0.8830000162124634, 0.8769999742507935, 0.8700000047683716, 0.8640000224113464, 0.859000027179718, 0.8539999723434448, 0.8489999771118164, 0.8450000286102295, 0.8420000076293945, 0.8370000123977661, 0.8330000042915344, 0.8289999961853027, 0.824999988079071, 0.8230000138282776, 0.8190000057220459, 0.8169999718666077, 0.8130000233650208, 0.8019999861717224, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8119999766349792, 0.8069999814033508, 0.8069999814033508, 0.8080000281333923, 0.8090000152587891, 0.8109999895095825, 0.8119999766349792, 0.8130000233650208, 0.8159999847412109, 0.8180000185966492, 0.8190000057220459, 0.0, 0.8259999752044678, 0.828000009059906, 0.8320000171661377, 0.8370000123977661, 0.8420000076293945, 0.8450000286102295, 0.8500000238418579, 0.8550000190734863, 0.8600000143051147, 0.8669999837875366, 0.8730000257492065, 0.8830000162124634, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0099999904632568, 1.0299999713897705, 1.0360000133514404, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7260000109672546, 0.7129999995231628, 0.7080000042915344, 0.7059999704360962, 0.7059999704360962, 0.7070000171661377, 0.7129999995231628, 0.7229999899864197, 0.7360000014305115, 0.7549999952316284, 0.0, 0.0, 0.0, 0.0, 0.0]
scan2 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.059000015258789, 1.0470000505447388, 1.0329999923706055, 1.0180000066757202, 1.003999948501587, 0.9940000176429749, 0.9810000061988831, 0.9710000157356262, 0.9589999914169312, 0.9490000009536743, 0.9390000104904175, 0.9290000200271606, 0.9200000166893005, 0.9120000004768372, 0.9049999713897705, 0.8970000147819519, 0.8889999985694885, 0.8830000162124634, 0.8759999871253967, 0.8709999918937683, 0.8650000095367432, 0.859000027179718, 0.8539999723434448, 0.8489999771118164, 0.8450000286102295, 0.8420000076293945, 0.8370000123977661, 0.8320000171661377, 0.8270000219345093, 0.824999988079071, 0.8209999799728394, 0.8190000057220459, 0.8159999847412109, 0.8130000233650208, 0.8019999861717224, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8109999895095825, 0.8069999814033508, 0.8069999814033508, 0.8080000281333923, 0.8090000152587891, 0.8109999895095825, 0.8119999766349792, 0.8119999766349792, 0.8149999976158142, 0.8190000057220459, 0.8199999928474426, 0.0, 0.824999988079071, 0.828000009059906, 0.8330000042915344, 0.8370000123977661, 0.8410000205039978, 0.8460000157356262, 0.8500000238418579, 0.8550000190734863, 0.8610000014305115, 0.8669999837875366, 0.8730000257492065, 0.8820000290870667, 0.890999972820282, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0140000581741333, 1.027999997138977, 1.0429999828338623, 1.055999994277954, 1.0729999542236328, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7129999995231628, 0.7139999866485596, 0.7170000076293945, 0.7179999947547913, 0.722000002861023, 0.7279999852180481, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
X1 = laserToCart(scan1)
X2 = laserToCart(scan2)

In [77]:
t = np.matrix([[1,0,0],[0,1,0],[0,0,1]])
print(t)
v = np.asarray([1,1,1])
print(v)
v*t

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[1 1 1]


matrix([[1, 1, 1]])

In [64]:
def frameInLastFrame(X2, X1):
    for pt2 in X2:
        closest = [0,0]
        for pt1 in X1:
            if np.linalg.norm(pt2 - pt1) < np.linalg.norm(pt2 - closest):
                closest = pt1
        try:
            X2in1 = np.append(X2in1, [closest], axis=0)
        except:
            X2in1 = np.asarray([closest])
    return X2in1

In [43]:
X2in1 = frameInLastFrame(X2, X1)

In [44]:
np.sum(np.sqrt(np.sum((X2in1*X2in1), axis=1)))

60.983000218868256